size: "200x250"
url: "/assets/a4.jpg"
per_page: "5"
admin:
  size: "70x70"
  url: "assets/avata.jpg"
role:
  member: 1
product:
  index:
    size: "200x150"
  show:
    size: "350x400"
  comment:
    avatar_size: "30x30"
suggest:
  index:
    size: "50x50"
zero: 0
avatar:
  url: "avatar.jpg"
